### ISSUE TITLE
How to make it work on custom theme?

### ISSUE THREAD

**Issue by LuizSantos1** [leytech/Leytech_RedirectReviews#2]
Hi there,
Is there any tutorial on how to make it work on custom theme?
I use ultimo, I have changed the file to app/design/frontend/ultimo 
but still it does not work. I have checked rwd and it is working there...

Regards

**Comment by bluec** [comment]
I don't really use or support this extension any more, but the extension does not require any changes to theme files or anything else as it relies only on observing events, so when you say "I have changed the file to app/design/frontend/ultimo" what do you mean? Changed what file?

**Comment by LuizSantos1** [comment]
Hi there, I know that most developers have migrated to Magento 2, but
I have decided to stay with OpenMage - Magento LTS and most extensions for
Magento 1.9 works just fine. 

Anyway, below I will describe what I did: 

I am using Ultimo Theme, and I have tested disabling Ultimo Theme and
enabling Base and RWD Theme. On both works, changing the plugin config. 

On Base Theme, I need to enable jQuery, on RWD Theme, I need to disable it.


So far, so good. 

But I have tried to make it work on Ultimo Theme, and it did not work. 
This is what I did inicially: 
Copied to: app/design/frontend/ultimo/default/template/leytech/ratingstars/form.phtml

It did not work, so I have tried to follow Ultimo's structure path: 
app/design/frontend/ultimo/default/template/review/leytech/ratingstars/form.phtml

It also, did not work. 

So I have decided to change Ultimo's original review form.phtml code
so I have copied the module code from: 
app/design/frontend/base/default/template/review/leytech/ratingstars/form.phtml

To: 
app/design/frontend/ultimo/default/template/review/form.phtml


This time, it changed the form but the star ratings do not show up. 

Inspecting the page, I get this errors: 

`Uncaught TypeError: $(...).rateYo is not a function
    at HTMLDocument.<anonymous> (`

Is it an error caused by non-registered customers?

The only things I have different with Ultimo are 
bootstrap and font awesome plugins running as Ultimo use these libs.

I just needed to know how to override this behavior with Ultimo, as
Base and RWD Theme's are working fine. 

Regards.

**Comment by bluec** [comment]
You are talking about the [Leytech_RatingStars](https://github.com/leytech/Leytech_RatingStars) extension but this issue is on the Leytech_RedirectReviews extension!

I cannot help with theme customisation, but to be honest I would not use the Leytech_RatingStars extension, there are better ways to achieve the same effect.
